module.exports = {
    ticketName: 'ticket-',
    ticketDescription: 'Ticket geöffnet von',
    ticketCreate: '✅ Dein Ticket wurde erstellt',
    ticketAlreadyExist: 'Entschuldigung, aber du hast bereits ein offenes Ticket.',
    ticketNoPermissions: 'Entschuldigung, aber du hast keine Berechtigung, dies zu tun.',
    ticketError: 'Etwas ist schiefgegangen, versuche es später erneut.',
    ticketMessageTitle: 'Herzlich Willkommen, danke für das Eröffnen eines Tickets.',
    ticketMessageDescription: 'Der Support wird sich sofort um dein Ticket kümmern!\nUm das Ticket zu schließen klicke auf 📪\n\nThe support will take care of your Ticket immediately!\nTo close the Ticket, click on 📪',
    ticketClose: 'Close',
    ticketCloseEmoji: '📪',
    ticketLock: 'Lock',
    ticketLockEmoji: '🔒',
    ticketUnlock: 'Unlock',
    ticketUnlockEmoji: '🔓',
    ticketClaim: 'Claim',
    ticketClaimEmoji: '👋',
    ticketManage: 'Members',
    ticketManageEmoji: '➕',
    ticketManageMenuTitle: 'Wähle ein Mitglied aus.',
    ticketManageMenuEmoji: '❔',
    ticketCloseTitle: 'Das Ticket wird derzeit geschlossen...',
    ticketCloseDescription: 'Das Ticket wird in 5 Sekunden geschlossen.',
    ticketSuccessLocked: 'Das Ticket wurde erfolgreich gesperrt.',
    ticketAlreadyLocked: 'Dieses Ticket ist bereits gesperrt.',
    ticketSuccessUnlocked: 'Das Ticket wurde erfolgreich entsperrt.',
    ticketAlreadyUnlocked: 'Dieses Ticket ist bereits entsperrt.',
    ticketSuccessClaim: 'Das Ticket wurde erfolgreich übernommen von',
    ticketAlreadyClaim: 'Das Ticket wird bereits übernommen von',
    ticketDescriptionClaim: ', es wurde übernommen von ',
    ticketTranscriptMember: 'Mitglied:',
    ticketTranscriptTicket: 'Ticket:',
    ticketTranscriptClaimed: 'Übernommen:',
    ticketTranscriptModerator: 'Moderator:',
    ticketTranscriptTime: 'Zeit:',
    ticketMemberAdd: 'wurde zum Ticket hinzugefügt.',
    ticketMemberRemove: 'wurde aus dem Ticket entfernt.',
}
